export const ADD_BANK = 'ADD_BANK'
export const REMOVE_BANK = 'REMOVE_BANK'
export const DEPOSIT_MONEY_TO_BANK_ACCOUNT = 'DEPOSIT_MONEY_TO_BANK_ACCOUNT'
export const WITHDRAW_MONEY_FROM_BANK_ACCOUNT = 'WITHDRAW_MONEY_FROM_BANK_ACCOUNT'