// Bank.js
export const ADD_BANK = "ADD_BANK";
export const REMOVE_BANK = "REMOVE_BANK";
export const DEPOSIT_MONEY_TO_BANK_ACCOUNT = "DEPOSIT_MONEY_TO_BANK_ACCOUNT";
export const WITHDRAW_MONEY_FROM_BANK_ACCOUNT =
  "WITHDRAW_MONEY_FROM_BANK_ACCOUNT";
// Expenses.js
export const ADD_EXPENSE = "ADD_EXPENSE";
export const REMOVE_EXPENSE = "REMOVE_EXPENSE";
export const EDIT_EXPENSE = "EDIT_EXPENSE";
export const SET_EXPENSES = "SET_EXPENSES";
// Sells.js
export const ADD_A_SELL_ITEM = "ADD_A_SELL_ITEM";
export const REMOVE_A_SELL_ITEM = "REMOVE_A_SELL_ITEM";
export const MAKE_EMPTY_A_SELL_ITEMS = "MAKE_EMPTY_A_SELL_ITEMS";
export const REMOVE_ALL_SELL_ITEMS = "REMOVE_ALL_SELL_ITEMS";
export const ADD_A_CUSTOMER = "ADD_A_CUSTOMER";
export const REMOVE_CUSTOMERS = "REMOVE_CUSTOMERS";
export const ADD_SELL_UNDER_CUSTOMER_HISTORY =
  "ADD_SELL_UNDER_CUSTOMER_HISTORY";
export const ADD_A_PREV_DUE = "ADD_A_PREV_DUE";
export const INCREMENT_MEMO_NUMBER = "INCREMENT_MEMO_NUMBER";
export const START_SET_MEMO_NUMBER = "START_SET_MEMO_NUMBER";
export const SET_ADD_SELL_UNDER_CUSTOMER_HISTORY =
  "SET_ADD_SELL_UNDER_CUSTOMER_HISTORY";
export const ADD_A_TABLE = "ADD_A_TABLE";
// Stock.js
export const SET_STOCK = "SET_STOCK";
export const ADD_ITEM_TO_STOCK = "ADD_ITEM_TO_STOCK";
export const REMOVE_ITEM_FROM_STOCK = "REMOVE_ITEM_FROM_STOCK";
export const UPDATE_STOCK_ITEM = "UPDATE_STOCK_ITEM";
// Due.js
export const SET_DUE_TEXT_FILTER = "SET_DUE_TEXT_FILTER";
export const SET_DUE = "SET_DUE";
export const REMOVE_A_PREV_DUE = "REMOVE_A_PREV_DUE";
export const UPDATE_A_PREV_DUE = "UPDATE_A_PREV_DUE";
